VERILOG = ../src/msx.v ../src/ram.v ../src/vram.v ../src/rom.v ../src/gamerom.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/keyboard.v ../src/keymap.v ../src/keyrom.v ../src/keyram.v \
	  ../src/video.v ../src/hdmi.v ../src/ps2.v \
	  ../src/lattice/ecp5pll.sv \
	  ../src/sdram.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v \
	  ../src/osd/spi_ram_btn.v ../src/osd/spirw_slave_v.v \
	  ../src/jt49/jt49.v  ../src/jt49/jt49_exp.v ../src/jt49/jt49_eg.v \
      ../src/jt49/jt49_div.v ../src/jt49/jt49_noise.v ../src/jt49/jt49_cen.v \
	  ../src/dac.v

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

